### ISSUE TITLE
metadata error: <ParseException> Unable to parse.

### ISSUE THREAD

**Issue by debugtalk** [cwxyz007/vscode-hexo-utils#10]
My post is valid in hexo:

```yaml
---
title: 黑盒测试用例设计技术--边界值分析法
permalink: post/blackbox-testing-method-boundary-value-analysis
date: 2015/03/19
categories:
  - Testing
  - 功能测试
tags:
  - 测试设计
---

本文通过案例的形式，详细讲解黑盒测试用例设计技术中的边界值分析法。
```

However, when I focus on categories/tags view, the errors below occurred, and in the categories/tags I can not see the post.

```text
Hexo: Parse [ /Users/debugtalk/MyProjects/MyGitHub/debugtalk/source/_posts/黑盒测试用例设计技术--边界值分析法.md ] metadata error: <ParseException> Unable to parse. (line 11: '本文通过案例的形式，详细讲解黑盒测试用例设计技术中的边界值分析法。')
```
