### ISSUE TITLE
can't recognize Categories & Tags with this format

### ISSUE THREAD

**Issue by jiaqiangbandongg** [cwxyz007/vscode-hexo-utils#7]
[Front-matter | Hexo](https://hexo.io/docs/front-matter.html#Categories-amp-Tags)

categories:
\- Sports
\- Baseball
tags:
\- Injury
\- Fight
\- Shocking

**Comment by cwxyz007** [comment]
I have checked it out, and it works. This is my format

```yaml
--- 
title: Title
date: 2019-2-24 12:57:44
categories:
- Sports
- Baseball
tags:
- Injury
- Fight
- Shocking
---
```

![image](https://user-images.githubusercontent.com/14226737/53295333-02ec3480-3834-11e9-9ec9-361a1ffdbddc.png)
